# Generated by Django 3.1.14 on 2023-02-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20230218_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.CharField(default='NO', max_length=3),
        ),
    ]
