# Generated by Django 3.1.14 on 2023-02-18 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_auto_20230218_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_content',
            new_name='choice_text',
        ),
    ]
